#!/usr/bin/env python3
"""Regenerate ``clickyclicker/models/keycodes.py`` from the kernel headers.

The generated module is checked into the repository so that neither the build
nor the runtime depends on ``linux/input-event-codes.h`` being installed.  Run
this script by hand when targeting a newer kernel::

    ./tools/gen_keycodes.py           # regenerate the table
    ./tools/gen_keycodes.py --check   # verify it against this machine's headers

The header ships with the ``linux-libc-dev`` package on Debian/Ubuntu and with
``kernel-headers`` on Fedora/Arch.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from clickyclicker.models.keycodes import CODES  # noqa: E402

HEADER = Path("/usr/include/linux/input-event-codes.h")
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "clickyclicker" / "models" / "keycodes.py"

DEFINE_RE = re.compile(r"^#define\s+((?:KEY|BTN)_[A-Z0-9_]+)\s+(0x[0-9a-fA-F]+|\d+)\s*$")

# Aliases the kernel defines for readability; they collide with the canonical
# name for the same numeric code and would make the reverse lookup ambiguous.
SKIP = {
    "KEY_MIN_INTERESTING",
    "KEY_MAX",
    "KEY_CNT",
    "BTN_MISC",
    "BTN_MOUSE",
    "BTN_JOYSTICK",
    "BTN_GAMEPAD",
    "BTN_DIGI",
    "BTN_WHEEL",
    "BTN_TRIGGER_HAPPY",
}


def parse(header: Path) -> list[tuple[str, int]]:
    entries: list[tuple[str, int]] = []
    seen: set[str] = set()
    for line in header.read_text(encoding="utf-8").splitlines():
        match = DEFINE_RE.match(line)
        if match is None:
            continue
        name, raw = match.group(1), match.group(2)
        if name in SKIP or name in seen:
            continue
        seen.add(name)
        entries.append((name, int(raw, 0)))
    return entries


def check(entries: list[tuple[str, int]]) -> int:
    """Verify the checked-in table against the headers on this machine.

    Deliberately *not* a byte-for-byte comparison against freshly generated
    output.  The table is generated from whatever kernel headers happen to be
    installed, and those differ between distributions and kernel versions -- a
    table generated on a newer kernel legitimately contains codes an older one
    has never heard of.  Requiring equality would make the check fail on every
    machine except the one the table was last generated on.

    The invariant that actually matters is that the two never *disagree*: every
    symbol the local headers define must appear in the table with the same
    numeric value.  Extra symbols are fine and are reported for information.
    """
    checked_in = dict(CODES)
    missing: list[str] = []
    conflicting: list[str] = []

    for name, code in entries:
        if name not in checked_in:
            missing.append(f"{name} = {code}")
        elif checked_in[name] != code:
            conflicting.append(f"{name}: table says {checked_in[name]}, headers say {code}")

    if conflicting:
        print("error: the checked-in table contradicts the kernel headers:", file=sys.stderr)
        for line in conflicting:
            print(f"  {line}", file=sys.stderr)
        print(f"\nRegenerate it with:  {sys.argv[0]}", file=sys.stderr)
        return 1

    if missing:
        print(
            f"error: {len(missing)} symbol(s) in {HEADER} are absent from the table:",
            file=sys.stderr,
        )
        for line in missing[:20]:
            print(f"  {line}", file=sys.stderr)
        if len(missing) > 20:
            print(f"  ... and {len(missing) - 20} more", file=sys.stderr)
        print(f"\nRegenerate it with:  {sys.argv[0]}", file=sys.stderr)
        return 1

    extra = len(checked_in) - len(entries)
    print(f"keycode table is consistent with {HEADER} ({len(entries)} symbols checked)")
    if extra > 0:
        print(f"  it also carries {extra} symbol(s) from a newer kernel, which is expected")
    return 0


def main() -> int:
    verify_only = "--check" in sys.argv[1:]

    if not HEADER.exists():
        print(
            f"error: {HEADER} not found; install your kernel headers package",
            file=sys.stderr,
        )
        return 1

    entries = parse(HEADER)
    if not entries:
        print(f"error: no KEY_/BTN_ defines parsed from {HEADER}", file=sys.stderr)
        return 1

    if verify_only:
        return check(entries)

    # A numeric code can have several spellings (BTN_LEFT/BTN_TOUCH share 0x110
    # only across device types, but BTN_A/BTN_SOUTH genuinely alias).  The first
    # spelling encountered wins for the reverse map, which matches the order the
    # kernel header itself uses.
    lines = [
        '"""Linux input event codes.',
        "",
        "Generated by ``tools/gen_keycodes.py`` from ``linux/input-event-codes.h``.",
        "Do not edit by hand.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "#: Mapping of kernel symbol (``KEY_A``, ``BTN_LEFT``) to numeric event code.",
        "CODES: dict[str, int] = {",
    ]
    for name, code in entries:
        lines.append(f"    {name!r}: {code},")
    lines.append("}")
    lines.append("")
    lines.append("#: Reverse mapping, preferring the kernel's canonical spelling for aliases.")
    lines.append("NAMES: dict[int, str] = {}")
    lines.append("for _name, _code in CODES.items():")
    lines.append("    NAMES.setdefault(_code, _name)")
    lines.append("del _name, _code")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(entries)} codes to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
