#!/usr/bin/env python3
"""Regenerate ``clickyclicker/models/keycodes.py`` from the kernel headers.

The generated module is checked into the repository so that neither the build
nor the runtime depends on ``linux/input-event-codes.h`` being installed.  Run
this script by hand when targeting a newer kernel::

    ./tools/gen_keycodes.py

The header ships with the ``linux-libc-dev`` package on Debian/Ubuntu and with
``kernel-headers`` on Fedora/Arch.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HEADER = Path("/usr/include/linux/input-event-codes.h")
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "clickyclicker" / "models" / "keycodes.py"

DEFINE_RE = re.compile(r"^#define\s+((?:KEY|BTN)_[A-Z0-9_]+)\s+(0x[0-9a-fA-F]+|\d+)\s*$")

# Aliases the kernel defines for readability; they collide with the canonical
# name for the same numeric code and would make the reverse lookup ambiguous.
SKIP = {
    "KEY_MIN_INTERESTING",
    "KEY_MAX",
    "KEY_CNT",
    "BTN_MISC",
    "BTN_MOUSE",
    "BTN_JOYSTICK",
    "BTN_GAMEPAD",
    "BTN_DIGI",
    "BTN_WHEEL",
    "BTN_TRIGGER_HAPPY",
}


def parse(header: Path) -> list[tuple[str, int]]:
    entries: list[tuple[str, int]] = []
    seen: set[str] = set()
    for line in header.read_text(encoding="utf-8").splitlines():
        match = DEFINE_RE.match(line)
        if match is None:
            continue
        name, raw = match.group(1), match.group(2)
        if name in SKIP or name in seen:
            continue
        seen.add(name)
        entries.append((name, int(raw, 0)))
    return entries


def main() -> int:
    if not HEADER.exists():
        print(
            f"error: {HEADER} not found; install your kernel headers package",
            file=sys.stderr,
        )
        return 1

    entries = parse(HEADER)
    if not entries:
        print(f"error: no KEY_/BTN_ defines parsed from {HEADER}", file=sys.stderr)
        return 1

    # A numeric code can have several spellings (BTN_LEFT/BTN_TOUCH share 0x110
    # only across device types, but BTN_A/BTN_SOUTH genuinely alias).  The first
    # spelling encountered wins for the reverse map, which matches the order the
    # kernel header itself uses.
    lines = [
        '"""Linux input event codes.',
        "",
        "Generated by ``tools/gen_keycodes.py`` from ``linux/input-event-codes.h``.",
        "Do not edit by hand.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "#: Mapping of kernel symbol (``KEY_A``, ``BTN_LEFT``) to numeric event code.",
        "CODES: dict[str, int] = {",
    ]
    for name, code in entries:
        lines.append(f"    {name!r}: {code},")
    lines.append("}")
    lines.append("")
    lines.append("#: Reverse mapping, preferring the kernel's canonical spelling for aliases.")
    lines.append("NAMES: dict[int, str] = {}")
    lines.append("for _name, _code in CODES.items():")
    lines.append("    NAMES.setdefault(_code, _name)")
    lines.append("del _name, _code")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(entries)} codes to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
